name: Test and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            kafka_producer:
              - 'kafka_producer/**'
      
      - name: Set up Python
        if: steps.filter.outputs.kafka_producer == 'true'
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          
      # You can test your matrix by printing the current Python version
      - name: Display Python Version
        if: steps.filter.outputs.kafka_producer == 'true'
        run: python -c "import sys; print(sys.version)"
        
      - name: Install Dependencies
        if: steps.filter.outputs.kafka_producer == 'true'
        run: |
          cd kafka_producer
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Kafka Producer Tests
        if: steps.filter.outputs.kafka_producer == 'true'
        run: |
          cd kafka_producer
          pip install pytest
          pytest tests.py

  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            kafka_broker:
              - 'kafka_broker/**'
            kafka_producer:
              - 'kafka_producer/**'
            kafka_consumer:
              - 'kafka_consumer/**'
      
      - name: Configure AWS Credentials
        if: steps.filter.outputs.kafka_broker == 'true' || steps.filter.outputs.kafka_producer == 'true' || steps.filter.outputs.kafka_consumer == 'true'
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Sync to S3
        if: steps.filter.outputs.kafka_broker == 'true' || steps.filter.outputs.kafka_producer == 'true' || steps.filter.outputs.kafka_consumer == 'true'
        run: |
          aws s3 sync --delete ./kafka_broker s3://citibike-data-platform-project-bucket/kafka_broker
          aws s3 sync --delete ./kafka_producer s3://citibike-data-platform-project-bucket/kafka_producer
          aws s3 sync --delete ./kafka_consumer s3://citibike-data-platform-project-bucket/kafka_consumer
      
      - name: Get EC2 Instance Public IPs
        if: steps.filter.outputs.kafka_broker == 'true' || steps.filter.outputs.kafka_producer == 'true' || steps.filter.outputs.kafka_consumer == 'true'
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances --filters Name=tag:Name,Values=citibike-kafka-broker Name=instance-state-name,Values=running --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "CITIBIKE_KAFKA_BROKER_HOST=$PUBLIC_IP" >> $GITHUB_ENV
          PUBLIC_IP=$(aws ec2 describe-instances --filters Name=tag:Name,Values=citibike-kafka-producer Name=instance-state-name,Values=running --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "CITIBIKE_KAFKA_PRODUCER_HOST=$PUBLIC_IP" >> $GITHUB_ENV
          PUBLIC_IP=$(aws ec2 describe-instances --filters Name=tag:Name,Values=citibike-kafka-consumer Name=instance-state-name,Values=running --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "CITIBIKE_KAFKA_CONSUMER_HOST=$PUBLIC_IP" >> $GITHUB_ENV
      
      - name: Get Broker EC2 Instance Private IP
        if: steps.filter.outputs.kafka_broker == 'true' || steps.filter.outputs.kafka_producer == 'true' || steps.filter.outputs.kafka_consumer == 'true'
        run: |
          PRIVATE_IP=$(aws ec2 describe-instances --filters Name=tag:Name,Values=citibike-kafka-broker Name=instance-state-name,Values=running --query 'Reservations[0].Instances[0].PrivateIpAddress' --output text)
          echo "BROKER_PRIVATE_IP_ADDRESS=$PRIVATE_IP" >> $GITHUB_ENV

      - name: Deploy Kafka Broker to EC2
        if: steps.filter.outputs.kafka_broker == 'true'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.CITIBIKE_KAFKA_BROKER_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo snap install aws-cli --classic
            sudo snap install docker
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region us-east-1
            rm -rf kafka_broker
            mkdir kafka_broker
            cd kafka_broker
            aws s3 sync --delete s3://citibike-data-platform-project-bucket/kafka_broker .
            echo "BROKER_PRIVATE_IP_ADDRESS=${{ env.BROKER_PRIVATE_IP_ADDRESS }}" > .env
            sudo docker compose down
          # sudo docker compose up -d --force-recreate

      - name: Deploy Kafka Producer to EC2
        if: steps.filter.outputs.kafka_producer == 'true'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.CITIBIKE_KAFKA_PRODUCER_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo snap install aws-cli --classic
            sudo snap install docker
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region us-east-1
            rm -rf kafka_producer
            mkdir kafka_producer
            cd kafka_producer
            aws s3 sync --delete s3://citibike-data-platform-project-bucket/kafka_producer .
            echo "BROKER_PRIVATE_IP_ADDRESS=${{ env.BROKER_PRIVATE_IP_ADDRESS }}" > .env
            sudo docker compose down
            sudo docker compose build
          # sudo docker compose up -d --force-recreate

      - name: Deploy Kafka Consumer to EC2
        if: steps.filter.outputs.kafka_consumer == 'true'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.CITIBIKE_KAFKA_CONSUMER_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo snap install aws-cli --classic
            sudo snap install docker
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region us-east-1
            rm -rf kafka_consumer
            mkdir kafka_consumer
            cd kafka_consumer
            aws s3 sync --delete s3://citibike-data-platform-project-bucket/kafka_consumer .
            echo "BROKER_PRIVATE_IP_ADDRESS=${{ env.BROKER_PRIVATE_IP_ADDRESS }}" > .env
            sudo docker compose down
            sudo docker compose build
          # sudo docker compose up -d --force-recreate
